1.8/Dockerfile.rhel7, 1.8/s2i/bin/usage
Fix usage and remove beta name from LABEL
=> Use OSE-3.2 repo for nss_wrapper

1.8/cccp.yml
Added comment to existing 1.6 container and added one
for 1.8.
=> Added cccp.yml file in 1.8 for container pipeline.

1.6/Dockerfile.rhel7, 1.8/Dockerfile.rhel7
Labels now should follow spec at https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md
=> New labels for OSBS

1.6/test/run, 1.8/test/run
This may lead to conflicts with tests for different repository.
@hhorak Please take a look.
=> Do not publish a container's port(s) to the host in tests

1.8/README.md
Small change to update documentation for S2I capabilities. 
More info is available in usage.
=> S2I documentation update

test/test-lib-openshift.sh
The templates will reside in
https://github.com/sclorg/nginx-ex/tree/master/openshift/templates
=> Add symlink to test-lib-openshift.sh in test dir.

1.10/test/run, 1.12/test/run, 1.8/test/run
Similarily to: sclorg/s2i-python-container#229
=> tests: replace removed s2i flag

1.10/Dockerfile, 1.10/Dockerfile.rhel7, 1.10/README.md, 1.12/Dockerfile, 1.12/Dockerfile.fedora, 1.12/Dockerfile.rhel7, 1.12/README.md, 1.8/Dockerfile, 1.8/Dockerfile.rhel7, 1.8/README.md
This is Pull Request from container-images/nginx repo.
It updates mainly LABELS.
=> Couple updates from container-images/nginx repo.

1.12/Dockerfile, 1.12/Dockerfile.fedora, 1.12/Dockerfile.rhel7, 1.12/README.md, 1.12/s2i/bin/assemble, 1.12/test/run, examples/1.12/test-app/nginx.conf, examples/1.12/test-app/nginx.conf.fedora
Please suggest how should I test this feature.
=> enable substituting nginx.conf

1.10/Dockerfile, 1.12/Dockerfile, 1.8/Dockerfile
It is not necessary to use testing repo now anymore, all packages are in released repo already.
=> Use released repos only

imagestreams/nginx-rhel7-ppc64le.json
add ppc64le imagestream for nginx 1.12
=> add ppc64le imagestream for nginx 1.12

1.12/Dockerfile.fedora
Remove release label - in Fedora it's updated automatically by build system.
+ make fedora Dockerfile more similar
@pkubatrh Please take a look and merge.
=> Fix Fedora image

1.10/Dockerfile, 1.10/Dockerfile.rhel7, 1.10/s2i/bin/run, 1.10/test/run
=> Sync 1.10 with 1.12/1.14.

1.12/Dockerfile.fedora
=> Remove hardcoded log files linking in dockerfile

imagestreams/nginx-centos7.json, imagestreams/nginx-rhel7-ppc64le.json, imagestreams/nginx-rhel7.json
This pull request removes a minor typo for all the image stream descriptions.
=> Removing Version Typo from Image Stream Descriptions

imagestreams/nginx-centos7.json, imagestreams/nginx-rhel7.json
per request from @siamaksade from OpenShift PM, this PR removes EOF version from the imagestream file
@hhorak @bparees
=> remove versions that are EOL

1.12/Dockerfile, 1.12/Dockerfile.fedora, 1.12/Dockerfile.rhel7, 1.14/Dockerfile, 1.14/Dockerfile.fedora, 1.14/Dockerfile.rhel7, 1.14/Dockerfile.rhel8
Install rh-nginx112-nginx-mod-stream
=> Resolves: #1753002 - RFE: Add rh-nginx112-mod-stream to the rhscl/nginx-112-rhel7 image 

imagestreams/nginx-rhel7.json
This pull request fixes only versions in openshift.io/display-name.
=> Fix openshift.io/display-name version

imagestreams/nginx-centos7.json, imagestreams/nginx-rhel7-s390x.json
Similar PR to sclorg/mariadb-container#115
=> Add imagestream file for s390x and add v1.16 to the centos imagestream

1.12/Dockerfile, 1.12/Dockerfile.fedora, 1.12/Dockerfile.rhel7, 1.12/s2i/bin/assemble, 1.12/test/perl-test-app/index.html, 1.12/test/perl-test-app/nginx-perl/Version.pm, 1.12/test/perl-test-app/nginx.conf, 1.12/test/run, 1.14/Dockerfile, 1.14/Dockerfile.fedora, 1.14/Dockerfile.rhel7, 1.14/Dockerfile.rhel8, 1.14/README.md, 1.14/s2i/bin/assemble, 1.14/test/perl-test-app/index.html, 1.14/test/perl-test-app/nginx-perl/Version.pm, 1.14/test/perl-test-app/nginx.conf, 1.14/test/run, 1.16/Dockerfile, 1.16/Dockerfile.fedora, 1.16/Dockerfile.rhel7, 1.16/Dockerfile.rhel8, 1.16/README.md, 1.16/s2i/bin/assemble, 1.16/test/perl-test-app/index.html, 1.16/test/perl-test-app/nginx-perl/Version.pm, 1.16/test/perl-test-app/nginx.conf, 1.16/test/run, examples/1.14/test-app/nginx.conf, examples/1.16/test-app/nginx.conf
Resolves issue #108 about adding support for the nginx perl module.
=> Add nginx-mod-http-perl module

1.14/test/run, 1.16/test/run, 1.18/test/run, test/check_imagestreams.py
This commit adds the check if latest version in present in imagestreams.
=> Adds check for the latest version in imagestreams

1.14/test/run, 1.16/test/run, 1.18/test/run
Run all tests and report results at the end.
This commit executes all tests and at the end
reports the whole summary for each version.
=> Run all tests and report results at the end

imagestreams/nginx-rhel-aarch64.json
This obsoletes https://github.com/sclorg/nginx-container/pull/124
=> Add aarch64 imagestreams

test/run
This commit fixes the catching result of each function.
If the testcase does not exist, then failure is caught.
=> Fix calling each testsuite and catch result

imagestreams/nginx-centos.json
Prefer quay images instead of dockerhub to avoid ratelimiting
=> imagestreams: point 1.14 centos image to quay

1.14/test/test-lib-remote-openshift.sh, 1.16/test/test-lib-remote-openshift.sh, 1.18/test/test-lib-remote-openshift.sh, test/run-openshift-remote-cluster, test/test-lib-remote-openshift.sh
Commit updates container-common-scripts.
and supports testing nginx-container under OpenShift 4
environment.
=> Support testing nginx-container under OpenShift 4

test/examples, test/run
This pull request adds an examples symlink into the test directory.
=> Fix symlink to examples

.github/workflows/centos7-openshift-tests.yaml, .github/workflows/centos7-tests.yaml, .github/workflows/fedora-tests.yaml, .github/workflows/rhel7-openshift-tests.yaml, .github/workflows/rhel7-openshift4-tests.yaml, .github/workflows/rhel7-tests.yaml, .github/workflows/rhel8-tests.yaml
=> Add support for GitHub Actions

.github/workflows/centos7-openshift-tests.yaml, .github/workflows/centos7-tests.yaml, .github/workflows/fedora-tests.yaml
=> Fix GitHub Actions for Fedora and CentOS 7

.github/workflows/build-and-push.yml
=> Add build and push GitHub Action

README.md
=> Version number typo

.github/workflows/build-and-push.yml
Also CentOS7 packages are present here:
http://mirror.centos.org/centos/7/sclo/x86_64/rh/Packages/r/
Let's enable builds and also pushing into
quay.io/centos7/nginx-120-centos7
=> NginX-1.20 is out and available

.github/workflows/container-tests.yml
- remove SHA step
- remove passing secrets
=> correct container-tests

.github/workflows/build-and-push.yml
Using the new build-and-push-action [1].
[1] https://github.com/sclorg/build-and-push-action
=> use new build-and-push action

.github/workflows/build-and-push.yml
- enable build-and-push only for sclorg repositories
- schedule automatic rebuild on wednesdays
=> schedule automatic rebuild on wednesdays

.github/workflows/container-tests.yml
=> Add support for testing redis-container in CentOS Stream 8

.github/workflows/build-and-push.yml, 1.18/Dockerfile.c8s, 1.18/README.md, 1.20/Dockerfile.c8s, 1.20/README.md, README.md
This pull request adds support CentOS Stream 8 for nginx-container.
It also updates README.md files and build-and-push action.
=> Support C8S for nginx-container

.github/workflows/container-tests.yml
=> Use CentOS Stream 8 for Fedora testing

.github/workflows/container-tests.yml
=> Use Fedora host system for testing Fedora images

.github/workflows/openshift-tests.yml
=> Use Testing Farm as GitHub Action for OpenShift tests.

.github/workflows/container-tests.yml, .github/workflows/openshift-tests.yml
=> Add the latest container-common-scripts and new compose

.github/workflows/container-tests.yml, .github/workflows/openshift-tests.yml
This pull request tests nginx-versions separately
=> Support testing versions separatelly

test/run-openshift-remote-cluster, test/test-openshift.yaml
This pull request brings support for testing nginx-container in CVP pipeline.
=> CVP pipeline supports

1.18/test/test-openshift.yaml, 1.20/test/test-openshift.yaml, 1.22/test/test-openshift.yaml
=> Add missing test-openshift.yaml files

.github/workflows/container-tests.yml, .github/workflows/openshift-tests.yml
=> Add support for testing 1.22-micro

.github/workflows/build-and-push.yml
Not sure how to test this before merging though. @zmiklank, please, take a look.
=> Use the same context for Build and Push action as it is used in the Makefile

test/test-lib-nginx.sh
This pull request adds support for testing imagestreams also on RHEL9
=> Support testing imagestreams on RHEL9

1.22-micro/Dockerfile.fedora, 1.22-micro/Dockerfile.rhel8, 1.22/Dockerfile.fedora, test/run, test/test-lib-nginx.sh
This pull request enables building and testing Nginx-1.22 container on RHEL8
=> Enable building and testing Nginx-1.22 on RHEL8

.github/dependabot.yml
This PR adds configuration for dependabot which will once a week check state of common/ and create PR with updated common/ if that is needed.
=> use dependabot for periodically updating common/

.github/dependabot.yml
=> remove labels from dependabot.yml, as we do not use them anywhere

1.24/Dockerfile.c9s, 1.24/Dockerfile.rhel8
=> remove .devel-repo file for nginx 1.22, RHEL8 + update nginx version in 1.24 dockerfiles

.github/workflows/container-tests.yml, .github/workflows/openshift-tests.yml
Reverts sclorg/nginx-container#267
Let's create a new action for testing. Only containers are needed.
=> Revert "temporary commit for testing nginx with new tfaga"

.github/workflows/build-and-push.yml, 1.24/Dockerfile.c8s, 1.24/Dockerfile.c9s, 1.24/Dockerfile.fedora, 1.24/Dockerfile.rhel8, 1.24/Dockerfile.rhel9
This pull request allows testing nginx 1.24 for C9s, C8s, rhel8, and rhel9.
Dockerfile.rhel8 is added for version 1.24
Also, build and push is updated for C9s and C8s.
=> Add nginx 1.24 for rhel8 and rhel9

.github/workflows/container-tests.yml, .github/workflows/openshift-tests.yml
=> tests: use per job parallel group

.github/workflows/build-and-push.yml
Depends on: https://github.com/sclorg/build-and-push-action/pull/34
=> automatically update image description to quay.io

.github/workflows/check-imagestreams.yml, imagestreams/imagestreams.yaml, imagestreams/nginx-centos.json, imagestreams/nginx-rhel-aarch64.json, imagestreams/nginx-rhel.json
=> Imagestream files generated by imagestream generator

imagestreams/imagestreams.yaml, imagestreams/nginx-centos.json, imagestreams/nginx-rhel-aarch64.json, imagestreams/nginx-rhel.json, test/test-lib-nginx.sh
=> Add missing imagestreams for Nginx-1.24

imagestreams/imagestreams.yaml, imagestreams/nginx-centos.json, imagestreams/nginx-rhel-aarch64.json, imagestreams/nginx-rhel.json, test/test-lib-nginx.sh
=> remove Nginx-1.24 imagestream till GA

imagestreams/imagestreams.yaml, imagestreams/nginx-centos.json, imagestreams/nginx-rhel-aarch64.json, imagestreams/nginx-rhel.json
This pull request adds imastreams for RHEL9.4
=> Add imagestreams Nginx-124 for RHEL9

.github/workflows/openshift-pytests.yml
This pull request adds support for testing Nginx-container in OpenShift by PyTest suite
https://github.com/sclorg/container-ci-suite
=> Add GitHub Action for running testing written in PyTest

test/run-openshift-pytest
Let's use Python3.12 as we decided globally.
=> Use Python 3.12 for pytest and option -rA

test/test_nginx_imagestream_s2i.py, test/test_nginx_imagestreams.py, test/test_nginx_local_example.py, test/test_nginx_remote_example.py, test/test_nginx_template_example_app.py
=> Use VERSION instead of SINGLE_VERSION like we do in whole org

.github/workflows/auto-merge-on-demand.yml, .github/workflows/auto-merge.yml
=> ci: use auto-merge wrapper

.github/workflows/container-tests.yml
=> Allow testing nginx-container on C10S host

.github/auto-merge.yml
=> Fix target-branch variable

1.20/test/run-openshift, 1.20/test/test_helm_nginx_imagestreams.py, 1.20/test/test_helm_nginx_template.py, 1.22/test/run-openshift, 1.22/test/test_helm_nginx_imagestreams.py, 1.22/test/test_helm_nginx_template.py, 1.24/test/test_helm_nginx_imagestreams.py, 1.24/test/test_helm_nginx_template.py, 1.26/test/run-openshift, test/test_helm_nginx_imagestreams.py, test/test_helm_nginx_template.py
=> Remove `run-openshift` that are deprecated. Adds helm charts tests

1.26/Dockerfile.c9s, 1.26/Dockerfile.rhel9
Remove exclude files. Allow building nginx-126 on RHEL9 and C9S
=> Allow building and testing Nginx-1.26 on RHEL9 and C9S

.github/workflows/build-and-push.yml, .github/workflows/container-tests.yml
The current version has been retired
https://ubuntu.com/about/release-cycle
=> Switch ubuntu-20.04 to ubuntu-latest
