sclorg/nginx-container

- 1.6/Dockerfile.rhel7
Enabling host repositories didn't work with docker 1.10 and newer inside OpenStack. It was fixed in latest rhel7 base release, so using 'rhel7' base image is required for RHEL CI. Postgresql PR - sclorg/postgresql-container#150
Also to enable repositories inside container running 'yum' first is required - see https://access.redhat.com/solutions/1443553 . Similar to sclorg/s2i-base-container#99 .
@hhorak @bparees Please take a look and merge.
> Fix using subscription in container

- 1.8/Dockerfile
For centos/ namespaced images use centos/ namespaced s2i base image. This image is based on https://github.com/sclorg/s2i-base-container/ and is built by coreservices-jenkins maintained by RHSCL team.
@hhorak @bparees Please take a look and merge.
> Use centos/ namespaced s2i base image

- 1.10/Dockerfile
- 1.10/Dockerfile.rhel7
- 1.12/Dockerfile
- 1.12/Dockerfile.fedora
- 1.12/Dockerfile.rhel7
- 1.8/Dockerfile
- 1.8/Dockerfile.rhel7
It's rationalized in https://github.com/sclorg/httpd-container/issues/30
Ideally this should be reverted once OpenShift Online is fixed.
> Do not use VOLUMES because it fails in OpenShift Online

- 1.10/test/run-openshift
- 1.10/test/test-lib-openshift.sh
- 1.10/test/test-lib.sh
- 1.12/test/run-openshift
- 1.12/test/test-lib-openshift.sh
- 1.12/test/test-lib.sh
- 1.8/test/run-openshift
- 1.8/test/test-lib-openshift.sh
- 1.8/test/test-lib.sh
- examples/1.8/test-app/nginx-default-cfg/alias.conf
- test/run-openshift
This kinda obsoletes #35, but it should be simpler, because it re-uses general functions freshly added into `test-lib-openshift.sh`.
> Run openshift tests

- examples/README.md
When running an s2i build the following error message occurred:
> error: build error: provided context directory does not exist: examples/1.12/test/test-app
Removed the "test" folder from the path to reflect the current location of test-app.
> Update context-dir path

- 1.10/Dockerfile
- 1.10/root/opt/app-root/nginxconf.sed
- 1.12/Dockerfile
- 1.12/root/opt/app-root/nginxconf.sed
- 1.8/Dockerfile
- 1.8/root/opt/app-root/nginxconf.sed
Per upstream nginx images, just symlink the default log files to the stdout/err devices and dont bother trying to reconfigure the nginx.conf file
https://stackoverflow.com/questions/22541333/have-nginx-access-log-and-error-log-log-to-stdout-and-stderr-of-master-process/42369571#42369571
https://github.com/nginxinc/docker-nginx/issues/87
https://github.com/nginxinc/docker-nginx/blob/master/mainline/alpine/Dockerfile#L136-L137
Closes #53
> Fix stdout by follow upstream logging practices for nginx in docker

- 1.10/test/run
- 1.12/test/run
- 1.14/test/run
When running with podman older than 1.1.0, which does not have cp command,
the test failed. This way the test does pretty much the same thing, but allows
to run it successfully with older podman as well.
> Replace docker cp with docker exec <cont> cat

- 1.10/s2i/bin/assemble
- 1.12/Dockerfile.fedora
- 1.12/s2i/bin/assemble
- 1.14/Dockerfile.fedora
- 1.14/s2i/bin/assemble
- 1.16/s2i/bin/assemble
Otherwise we can see permissions denied in cases the files copied into
/usr/share did not have correct permissions on the host originaly.
It looked like this in the test log:
/usr/share/container-scripts/nginx/common.sh: line 33: /usr/share/container-scripts/nginx/nginx-start/init.sh: Permission denied
> Fix persmissions for all files given in s2i

- imagestreams/nginx-centos7.json
- imagestreams/nginx-rhel7-ppc64le.json
- imagestreams/nginx-rhel7-s390x.json
- imagestreams/nginx-rhel7.json
Order is now: latest, 1.16, and 1.14.
We would like to test if the latest version is present in the imagestreams.
It is done by ansible-script (sclorg/ansible-tests#4)
The second tag is going to be used for test if the version is the latest.
> Reorder imagestreams

- 1.12/test/imagestreams
- 1.14/test/imagestreams
- 1.16/test/imagestreams
- test/imagestreams
- test/run-openshift-local-cluster
- test/run-openshift-remote-cluster
- test/test-lib-nginx.sh
- test/test-lib.sh
This PR combines more changes:
- add image stream test
- adopts new functions refactored in https://github.com/sclorg/container-common-scripts/pull/155/files
- enables tests to be run in a remote OCP4 cluster
> Use refactored functions and enable testing in remote OCP4

- 1.16/README.md
The s2i command in the example fails with three dashes.
> Typo having extra dash

- 1.10/root/opt/app-root/nginxconf.sed
- 1.12/root/opt/app-root/nginxconf.sed
- 1.14/root/opt/app-root/nginxconf-fed.sed
- 1.14/root/opt/app-root/nginxconf.sed
- 1.16/root/opt/app-root/nginxconf-fed.sed
- 1.16/root/opt/app-root/nginxconf.sed
- 1.18/root/opt/app-root/nginxconf-fed.sed
- 1.18/root/opt/app-root/nginxconf.sed
This should be avoid error like
```
2018/11/05 16:36:55 [error] 28#0: *208 open() "/opt/app-root/src/50x.html" failed (2: No such file or directory), client: ::1, server: _, request: "GET /nonexist/api/v1/ping HTTP/1.1", upstream: "http://localhost:8081/nonexist/api/v1/ping ", host: "localhost:8080"
::1 - - [05/Nov/2018:16:36:55 +0100] "GET /nonexist/api/v1/ping HTTP/1.1" 404 162 "-" "curl/7.29.0" "-"
```
Normally this should be a 50x error but a 404 is return.
Adding try_files behavior to possible provide custom error pages inside `/opt/app-root/src/`
> Remove error page configuration.

- imagestreams/nginx-centos.json
Let's do not merge yet, there are ongoing discussions whether nginx container image is gonna be released as a UBI -- in that case, we can avoid building CentOS 8 images.
> Add CentOS 8 image streams

- 1.14/Dockerfile
- 1.14/README.md
- 1.16/Dockerfile
- 1.16/README.md
- 1.18/Dockerfile
- 1.18/README.md
- README.md
- imagestreams/nginx-centos.json
Update README.md and Dockerfile
This commit updates README.md files and Dockerfile
which are used for building CentOS 7
> Support registry Quay.io instead of Docker.io

- 1.16/README.md
- 1.16/s2i/bin/usage
- 1.18/README.md
- 1.18/s2i/bin/usage
- examples/Dockerfile
- examples/Dockerfile.s2i
- examples/README.md
- test/run
This PR depends on #128 that needs to be merged first.
This adds the following enhancements:
- Dockerfile examples for a variant that uses s2i scripts and a variant without s2i scripts
- Documentation enhancement that describes how the image can be used using a Dockerfile
- A test for the example Dockerfiles
This is a similar pull-request as sclorg/httpd-container#99., sclorg/s2i-nodejs-container#247 and sclorg/s2i-perl-container#192
To see the formatted README.md, see https://github.com/hhorak/nginx-container/blob/doc-dockerfile/1.18/README.md and it is also visible in the catalog, which will be the most important view: https://catalog.redhat.com/software/containers/detail/5f521a6f9dd2d5ca7158e5dc
>  Document usage with a Dockerfile

- README.md
Images are EOL since Nov 2020.
nginx-1.14 for RHEL8 is still supported
> Deprecate nginx-1.14 for RHEL7 and CentOS7

- 1.16/README.md
- 1.18/README.md
- examples/Dockerfile.s2i
- test/run
I found this `--chown` option of `ADD` statement in the Dockerfile today, it seems like much better way to set correct permissions to make the assemble script work.
> Use --chown option for ADD when adding app source instead of changing USER

- 1.14/Dockerfile.rhel7
- 1.16/Dockerfile.rhel7
- 1.18/Dockerfile.rhel7
The Dockerfile.rhel7 contains typo. Instead of rh-nodejs, there should be rh-nginx
> Typo in RHEL7 Dockerfile

- imagestreams/nginx-centos.json
Reverts sclorg/nginx-container#143
Picked the wrong quay.io organization (`centos7`) for centos8 image.
https://quay.io/organization/centos8 is blank, so reverting to dockerhub.
@phracek PTAL
> Revert "imagestreams: point 1.14 centos image to quay"

- imagestreams/nginx-centos.json
nginx 1.16 CentOS8 tag should refer to CentOS8 image
> nginx-centos imagestream: fix 1.16 centos8 tag

- imagestreams/nginx-centos.json
- imagestreams/nginx-rhel-aarch64.json
- imagestreams/nginx-rhel.json
RHEL 8 nginx:1.14 is going out of support in May 2021.
> Remove 1.14-el8 imagestreams

- examples/1.20/test-app/index.html
- examples/1.20/test-app/index2.html
- examples/1.20/test-app/nginx-cfg/default.conf
- examples/1.20/test-app/nginx-default-cfg/alias.conf
- examples/1.20/test-app/nginx.conf
This pull request only adds examples for version 1.20.
Missing examples cause testing errors for Fedora https://github.com/sclorg/nginx-container/pull/154
Especially see: https://github.com/sclorg/nginx-container/pull/154#issuecomment-916021333
Why does this happen?
In the test Dockerfile{.s2i} we are cloning https://github.com/nginx-container repository https://github.com/sclorg/nginx-container/blob/master/test/run#L424
and use function  https://github.com/sclorg/container-common-scripts/blob/master/test-lib.sh#L834
But in the case of new versions, the official repository does not contain corresponding version in examples yet ;)
> Add examples 1.20

- imagestreams/nginx-centos.json
- imagestreams/nginx-rhel-aarch64.json
- imagestreams/nginx-rhel.json
- Update imagestreams for RHEL 8.5 and RHSCL 3.8
- Use groupified apiVersion
> Update imagestreams for RHEL 8.5 and RHSCL 3.8

- .github/workflows/build-and-push.yml
- .github/workflows/docker-tests.yml
Add support for testing nginx-container under CentOS Stream 9
Add support for pushing nginx-container as CentOS Stream 9 image
to quay.io
> Add support for testing nginx-container under CentOS Stream 9

- .github/workflows/build-and-push.yml
- 1.20/Dockerfile.c9s
- test/run
This pull request adds support for building and testing `nginx-container` under CentOS Stream 9.
What was changed in `Dockerfile.c9s`?
This code have been added. 
```bash
chmod -R a+rwx ${NGINX_LOG_PATH} && \
chown -R 1001:0 ${NGINX_LOG_PATH} && \
```
otherwise symbolic links https://github.com/sclorg/nginx-container/blob/master/1.20/s2i/bin/run#L12 and https://github.com/sclorg/nginx-container/blob/master/1.20/s2i/bin/run#L13 are not working properly. It shows, permission denied.
The privileges are:
```bash
d rwx root:root /var/log/nginx
```
and as a user 1001, we are not able to create a symbolic link there.
See Dockerfile.c9s change:
```bash
$ diff 1.20/Dockerfile.rhel8 1.20/Dockerfile.c9s
1c1
< FROM ubi8/s2i-core:1
---
> FROM quay.io/sclorg/s2i-base-c9s:c9s
26c26
< …
```
> Support CentOS Stream 9

- .github/workflows/container-tests.yml
This pull request adds support to tests driven by https://github.com/sclorg/testing-farm-as-github-action
As soon as tests are working well, then `docker-tests.yml` file will be removed.
> Use testing-farm-as-github-action for container-tests

- .github/workflows/container-tests.yml
GitHub offers information about specific action in its embedded variables.
Pull request number can be from the `issue_comment` event gathered via this variable:
```
${{ github.event.issue.number }}
```
This change was tested on testing repository:
https://github.com/zmiklank/test_github_actions/pull/6
Pull request number was correctly gathered, as can be seen in this GitHub action:
https://github.com/zmiklank/test_github_actions/runs/5466813043?check_suite_focus=true
> get PR number from github.event.issue.number variable

- test/run-openshift-remote-cluster
- test/test-lib-nginx.sh
This PR also enables `test_nginx_imagestream`, which was disabled.
> run all openshift4 tests even if one fails

- .github/workflows/container-tests.yml
This can be merged only when TFGA v1.2.9 is released (with this change integrated: https://github.com/sclorg/testing-farm-as-github-action/pull/40)
> update container-tests to use newest testing farm action

- 1.20/Dockerfile.fedora
This is a proposal for fixing https://github.com/sclorg/nginx-container/issues/166 and closing https://github.com/sclorg/nginx-container/pull/187.
For now it is only for v1.20 in Fedora, but can probably be extended also to other distributions, if it passes a code-review.
Explanation can be found in commit messages.
> Change permissions in Fedora image

- 1.22/test/test-app
This is just a minor fix for a copy&paste error. No real implications, as the example apps are the same.
> Fix symlink for the test app

- 1.20/Dockerfile.rhel9
- 1.20/README.md
- README.md
This pull request adds support for building and testing nginx-120 container on RHEL9 host.
Including testing on OpenShift 4.
> Add support for building and testing nginx-container on RHEL9

- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
RHEL-9.1.0 does not exist yet in subscriptions
and therefore tests for RHEL9 are failing
during machine initialization
> Use compose RHEL-9.0.0 instead of RHEL-9.1.0

- 1.18/test/test-lib-remote-openshift.sh
- 1.20/test/test-lib-remote-openshift.sh
- 1.22/test/test-lib-remote-openshift.sh
- test/run-openshift-remote-cluster
Symlinks points to test directory instead of `common`.
In dist-git, the links are broken
Closes: #117
> Fixes: #117 Call tagging image after OpenShift is logged in

- test/run-openshift-remote-cluster
This would need a support in container-common-scripts.
> Using OC_ERR variable for OC failures

- 1.22-micro/Dockerfile.fedora
This is not possible in RHEL8 yet unfortunately, as there is no `nss_wrapper-libs` package available.
> Use nss_wrapper-libs only to get rid of perl

- 1.18/Dockerfile
- 1.20/Dockerfile
If we leave $NGINX_VERSION there the command fails, because $NGINX_VERSION is substituted with "".
This is caused by docker->podman change.
This fix is only workaround.
Strange is, that when I print value of $NGINX_VERSION directly in the Dockerfile it is set correctly to either 1.20 or 1.18.
The reason of this issue in not a invalid build context, the behavior would be different then.
Unfortunately it seems that all other sclorg containers are affected by this too.
> centos7: use hardcoded VERSION in COPY command in Dockerfile

- imagestreams/nginx-centos.json
- imagestreams/nginx-rhel-aarch64.json
- imagestreams/nginx-rhel.json
Nginx will reach EOL in November 2022 for CentOS 7, RHEL7, and for RHEL8.
> EOL imagestreams for Nginx 1.18.

- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
This PR proposes extracting duplicate code from the testing GitHub Actions in containers repositories and moving it to its own repository.
This new repository is not yet created and I would like to know what @phracek thinks about it before creating it.
The new repository would contain composite GitHub Action which will work as a wrapper around tfaga for sclorg use-cases.
This PR also shows what changes would need to be done in all of the container repositories in order to propagate this change.
It could seem like it would be better to have this new composite action in container-common-scripts repository. However, the composite action filename has to be `action.yml` and that is too non-descriptive to be included in the container-common-scripts repository.
We can try symlinks, but I …
> use sclorg-specific wrapper for tfaga

- 1.18/Dockerfile
- 1.18/Dockerfile.fedora
- 1.18/Dockerfile.rhel7
- 1.18/Dockerfile.rhel8
- 1.20/Dockerfile
- 1.20/Dockerfile.c9s
- 1.20/Dockerfile.fedora
- 1.20/Dockerfile.rhel7
- 1.20/Dockerfile.rhel8
- 1.20/Dockerfile.rhel9
- 1.22-micro/Dockerfile.c9s
- 1.22-micro/Dockerfile.fedora
- 1.22-micro/Dockerfile.rhel8
- 1.22/Dockerfile.c9s
- 1.22/Dockerfile.fedora
- 1.22/Dockerfile.rhel8
Nginx upstream [1] uses SIGQUIT for graceful shutdown even in their container images [2].
We switch to SIGQUIT too, as current default SIGTERM immediately closes opened connections.
[1] http://nginx.org/en/docs/control.html
[2] https://github.com/nginxinc/docker-nginx/issues/377
Resolves: https://github.com/sclorg/nginx-container/issues/242
> use SIGQUIT as a STOPSIGNAL in all images

- .github/workflows/container-tests.yml
- examples/1.24/test-app/index.html
- examples/1.24/test-app/index2.html
- examples/1.24/test-app/nginx-cfg/default.conf
- examples/1.24/test-app/nginx-default-cfg/alias.conf
- examples/1.24/test-app/nginx.conf
This pull request adds support for testing nginx-container with version 1.24.
The part of this pull request is also directory examples/1.24 which is needed for test https://github.com/sclorg/nginx-container/blob/master/test/run#L418
It clones https://github.com/sclorg/nginx-container where should be a directory 1.24.
> Support testing nginx-container 1.24

- 1.20/Dockerfile.fedora
- 1.22-micro/Dockerfile.fedora
- 1.22/Dockerfile.fedora
> migrate from f35/f36 to f37 for fedora images, as f35,f36 are now EOL

- .github/workflows/build-and-push.yml
- 1.24/Dockerfile.fedora
The "1.22/Dockerfile.fedora" and "1.22-micro/Dockerfile.fedora" has already their .exclude-files, so are not being tested. This PR disables their building and pushing to quay.io too.
> stop building usupported Fedora images + move nginx 1.24 Fedora image to f38 base

- test/run-openshift-local-cluster
- test/run-openshift-remote-cluster
- test/test-lib-nginx.sh
Move openshift tests to test-lib-nginx.sh and use it in OpenShift 4 as well
Call all functions as in OpenShift 3 as in OpenShift 4
> Move openshift tests to test-lib-nginx.sh and use it in OpenShift 4 as well

- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
Tfaga-wrapper provides new typescript-written tfaga in 'typescript' branch. This commit moves testing to this new tfaga.
Depends on: https://github.com/sclorg/testing-farm-as-github-action/pull/84
> temporary commit for testing nginx with new tfaga

- 1.22/test/run-openshift-remote-cluster
- 1.22/test/test-lib-nginx.sh
- test/test-lib-nginx.sh
This PR migrates DeploymentConfig to Deployment.
See more info here:
https://docs.openshift.com/container-platform/4.12/applications/deployments/what-deployments-are.html
Since OPenShift 4.14 DeploymentConfigs are deprecated: https://access.redhat.com/articles/7041372
See example PR here: https://github.com/sclorg/nginx-ex/pull/31
> This PR migrates DeploymentConfig to Deployment.

- imagestreams/nginx-centos.json
- imagestreams/nginx-rhel-aarch64.json
- imagestreams/nginx-rhel.json
Nginx 1.20 went EOL in November 2023: https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle and 1.22 was missing.
@yselkowitz FYI if you don't mind looking at the changes
> Add nginx 1.22 to imagestreams and remove ubi8/1.20

- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
We can use group based on issue number - so that on every PR only one parallel tests for containers and ocp could run.
Using ${{ github.head_ref }} is not valid for our use-case, see https://github.com/sclorg/nginx-container/actions/runs/8158453585
@jamacku PTAL.
> ${{ github.head_ref }} not available for issue comment trigger

- .github/workflows/openshift-tests.yml
This pull request adds testing nginx 1.24 container on OpenShift 4.
Container tests are already tested.
> Add testing NginX 1.24 container on OpenShift 4

- .github/workflows/build-and-push.yml
- 1.22-micro/README.md
- 1.24/README.md
- README.md
Wait until 31th of May for merge.
> deprecate c8s images, as EOL for c8s is 31th of May 2024

- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
Running tests is not needed. It only adds support into GitHub Action
This pull request blocks https://github.com/sclorg/nginx-container/pull/297
> Add support for testing Nginx 1.26 as container as openshift

- examples/1.26/test-app/index.html
- examples/1.26/test-app/index2.html
- examples/1.26/test-app/nginx-cfg/default.conf
- examples/1.26/test-app/nginx-default-cfg/alias.conf
- examples/1.26/test-app/nginx.conf
This is needed for passing tests https://github.com/sclorg/nginx-container/pull/297
We have a test run_dockerfiles_test that clones upstream repository and adds examples/<version> application.
But in case of new version it does not exist yet ;)
This pull request avoids failing tests.
> Add 1.26 examples directory

- .github/auto-merge.yml
- .github/workflows/auto-merge-on-demand.yml
- .github/workflows/auto-merge.yml
- .github/workflows/pr-metadata.yml
Add automation that will merge approved PRs with passed CI checks automatically.
It uses the following GitHub Actions:
* [gather-pull-request-metadata](https://github.com/redhat-plumbers-in-action/gather-pull-request-metadata) - to gather important data about PRs (used in following actions)
* [pull-request-validator](https://github.com/redhat-plumbers-in-action/pull-request-validator) - to check if PR is approved and has passed CI checks and more
* [auto-merge](https://github.com/redhat-plumbers-in-action/auto-merge) - to merge approved PRs
* [issue-commentator](https://github.com/redhat-plumbers-in-action/issue-commentator) - to comment on PR with status of PR and merge status
Here are some examples of use from the systemd source-git. Please notice the `Pull Request validation` and `Auto …
> Enable Automatic Merge of approved Pull Requests

- 1.20/test/run-openshift-pytest
- 1.20/test/test_nginx_imagestream_s2i.py
- 1.20/test/test_nginx_imagestreams.py
- 1.20/test/test_nginx_local_example.py
- 1.20/test/test_nginx_remote_example.py
- 1.22/test/run-openshift-pytest
- 1.22/test/test_nginx_imagestream_s2i.py
- 1.22/test/test_nginx_imagestreams.py
- 1.22/test/test_nginx_local_example.py
- 1.22/test/test_nginx_remote_example.py
- 1.24/test/run-openshift-pytest
- 1.24/test/test_nginx_imagestream_s2i.py
- 1.24/test/test_nginx_imagestreams.py
- 1.24/test/test_nginx_local_example.py
- 1.24/test/test_nginx_remote_example.py
- 1.24/test/test_nginx_template_example_app.py
- test/run-openshift-pytest
- test/test_nginx_imagestream_s2i.py
- test/test_nginx_imagestreams.py
- test/test_nginx_local_example.py
- test/test_nginx_remote_example.py
- test/test_nginx_template_example_app.py
Add test written in PyTest for testing
mysql-container in OpenShift 4 environment
Similar pull request is here:
https://github.com/sclorg/mariadb-container/pull/246
> Add tests written in PyTest for testing in Openshift 4

- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
- 1.20/README.md
- README.md
- imagestreams/imagestreams.yaml
- imagestreams/nginx-centos.json
- imagestreams/nginx-rhel.json
- test/run
- test/run-openshift-remote-cluster
This pull request removes RHEL-7 from this repository.
> Remove RHEL-7 support - EOL June 2024

- .github/workflows/build-and-push.yml
- 1.26/Dockerfile.c10s
- 1.26/Dockerfile.fedora
- 1.26/README.md
- README.md
This pull request contains three updates.
*  Adds Dockerfile.c10s for building and testing mariadb-container
*  Updates README's
*  Update build-and-push action
> Add support for Testing nginx-1.26 in CentOS Stream 10

- 1.22-micro/Dockerfile.rhel8
- 1.22/Dockerfile.fedora
- 1.22/Dockerfile.rhel8
- 1.22/Dockerfile.rhel9
- 1.24/Dockerfile.fedora
- 1.24/Dockerfile.rhel8
- 1.24/Dockerfile.rhel9
- 1.26/Dockerfile.c10s
- 1.26/Dockerfile.fedora
- 1.26/Dockerfile.rhel8
- 1.26/Dockerfile.rhel9
This pull request replaces nss_wrapper with nss_wrapper-libs
Less dependency and unnecessary footprint
> This pull request replaces nss_wrapper with nss_wrapper-libs

- 1.20/test/test_helm_nginx_imagestreams.py
- 1.20/test/test_helm_nginx_template.py
- 1.20/test/test_shared_helm_nginx_imagestreams.py
- 1.20/test/test_shared_helm_nginx_template.py
- 1.22/test/test_helm_nginx_imagestreams.py
- 1.22/test/test_helm_nginx_template.py
- 1.22/test/test_shared_helm_nginx_imagestreams.py
- 1.22/test/test_shared_helm_nginx_template.py
- 1.24/test/test_helm_nginx_imagestreams.py
- 1.24/test/test_helm_nginx_template.py
- 1.24/test/test_shared_helm_nginx_imagestreams.py
- 1.24/test/test_shared_helm_nginx_template.py
- 1.26/test/test_nginx_imagestream_s2i.py
- 1.26/test/test_nginx_imagestreams.py
- 1.26/test/test_nginx_local_example.py
- 1.26/test/test_nginx_remote_example.py
- 1.26/test/test_nginx_template_example_app.py
- 1.26/test/test_shared_helm_nginx_imagestreams.py
- 1.26/test/test_shared_helm_nginx_template.py
- test/test_shared_helm_nginx_imagestreams.py
- test/test_shared_helm_nginx_template.py
This pull request does not modify source neither tests. Only change order of test execution.
Container-ci-suite do no support switching between clusters.
> Fix helm charts order

- .github/workflows/container-tests.yml
- .github/workflows/openshift-pytests.yml
- .github/workflows/openshift-tests.yml
This pull request enables testing nginx-container on RHEL10 host.
It updates only Git Hub Action. No code is modifed.
> Enable testing nginx-container on RHEL10 host.

- 1.26/Dockerfile.rhel10
- 1.26/README.md
- README.md
This pull request supports building and testing nginx-container on RHEL 10 quest.
The first commit adds Dockerfile.rhel10 for building and testing.
The second commit updates README.md files
> Building and testing nginx-container on RHEL 10

- test/run-openshift-pytest
- test/test_nginx_imagestream_s2i.py
- test/test_shared_helm_nginx_imagestreams.py
- test/test_shared_helm_nginx_template.py
> Fix nginx-container OpenShift 4 tests

- test/test_nginx_imagestream_s2i.py
- test/test_nginx_local_example.py
- test/test_nginx_remote_example.py
- test/test_nginx_template_example_app.py
- test/test_shared_helm_nginx_template.py
This pull request enables testing nginx-container on shared cluster
The nginx-container code is not changed at all.
> Support testing nginx-container on shared_cluster

- 1.20/Dockerfile.rhel9
- 1.22/Dockerfile.rhel9
- 1.24/Dockerfile.rhel9
Replace 'bind-utils' with 'bind9.18-utils'
See Jira issue https://issues.redhat.com/browse/RHEL-80345
It is valid only for RHEL9
> Replace 'bind-utils' with 'bind9.18-utils'

- test/test_nginx_imagestream_s2i.py
- test/test_nginx_local_example.py
- test/test_nginx_remote_example.py
- test/test_nginx_template_example_app.py
For S2I builds do not use shared cluster
It has an issue with pulling image like ErrImagePull.
Needs more investigation.
> For S2I builds do not use shared cluster

- test/test_shared_helm_nginx_template.py
Do not test curl connection.
It does not make sense. We used 'helm test' that is enought.
> Do not test curl connection

- test/test_nginx_imagestream_s2i.py
- test/test_nginx_local_example.py
- test/test_nginx_remote_example.py
- test/test_nginx_template_example_app.py
- test/test_shared_helm_nginx_imagestreams.py
> Allow testing nginx-container on shared_cluster

- .github/workflows/container-pytest.yml
- 1.20/Dockerfile.rhel9
- 1.22/Dockerfile.rhel9
- 1.24/Dockerfile.rhel9
- 1.26/Dockerfile.rhel9
Add GitHub Action for running ContainerPytest suite
to nginx-container
> Add GitHub Action for running ContainerPytest suite
